<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1859" started-at="2019-04-23T22:36:49Z" finished-at="2019-04-23T22:36:51Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1859" started-at="2019-04-23T22:36:49Z" finished-at="2019-04-23T22:36:51Z">
      <class name="customer_api_test.api_test.customerservicetest_GET">
        <test-method status="PASS" signature="JSONIDdoesnotexist()[pri:0, instance:customer_api_test.api_test.customerservicetest_GET@326de728]" name="JSONIDdoesnotexist" duration-ms="1257" started-at="2019-04-23T15:36:49Z" finished-at="2019-04-23T15:36:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- JSONIDdoesnotexist -->
        <test-method status="FAIL" signature="testwithIDdoesnotexist()[pri:1, instance:customer_api_test.api_test.customerservicetest_GET@326de728]" name="testwithIDdoesnotexist" duration-ms="584" started-at="2019-04-23T15:36:50Z" finished-at="2019-04-23T15:36:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [500]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [500]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at customer_api_test.api_test.customerservicetest_GET.testwithIDdoesnotexist(customerservicetest_GET.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testwithIDdoesnotexist -->
      </class> <!-- customer_api_test.api_test.customerservicetest_GET -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
